- name: Vim configuration
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:

  - name: User facts
    setup:
      filter: '*user*'

  - name: User info
    set_fact:
      vimdir: '{{ ansible_facts.user_dir }}/.vim'

  - name: Main .vim directory
    copy:
      src: vim/
      dest: '{{ vimdir }}'
      directory_mode: 0755
      mode: 0644

  - name: Additional subdirs
    file:
      path: '{{ vimdir }}/{{ item }}'
      state: directory
      mode: 0755
    loop:
    - autoload
    - plugged

  - name: Vim-plug is installed
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: '{{ vimdir }}/autoload/'
      mode: 0644

  - name: Plugins are installed
    command: vim +'PlugInstall --sync' +qa
