# ~/.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#------------------------------------------------------------------------------#
#-- Sources
#------------------------------------------------------------------------------#

# Source all .sh files in .bashrc.d
# Directory and files MUST be owned by current user
# and have 700 and 600 perms respectively
bashrcd=~/.bashrc.d
if [[ $(stat -c '%f' "$bashrcd") == 41c0 && -O "$bashrcd" ]]; then
    shopt -s nullglob
    for f in "$bashrcd"/*.sh; do
        [[ $(stat -c '%f' "$f") == 8180 && -O "$f" ]] && {
            source "$f"
        }
    done
    shopt -u nullglob
fi

source /etc/profile.d/vte.sh # Workaround the CWD bug in GNOME Terminal
source /usr/share/git-core/contrib/completion/git-prompt.sh

#------------------------------------------------------------------------------#
#-- Variables
#------------------------------------------------------------------------------#
export LANG=en_US.utf8
export EDITOR=vim
export LESS=FRXS
export HISTCONTROL=ignoredups:ignorespace

export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1

BEGIN_PS1='[$(bred_if_nz $?)]$(venv_ps1)'
END_PS1='[\u@\h \W]\$ '
PROMPT_COMMAND="__git_ps1 '$BEGIN_PS1' '$END_PS1' '[%s]'; $PROMPT_COMMAND"
export PROMPT_COMMAND

export PATH=$PATH:$HOME/.local/bin

#------------------------------------------------------------------------------#
#-- Options
#------------------------------------------------------------------------------#
#shopt -s direxpand
