# ~/.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#------------------------------------------------------------------------------#
#-- Aliases
#------------------------------------------------------------------------------#
alias eog=xviewer
alias evince=xreader
alias gw='git what'
alias ls='LANG=C ls --color=auto'


#------------------------------------------------------------------------------#
#-- Functions
#------------------------------------------------------------------------------#

# Include the python venv name in purple if it exists
function venv_ps1() {
    if [ -n "$VIRTUAL_ENV" ]; then
        printf '[\001\e[35m\002%s\001\e[0m\002]' "$(basename $VIRTUAL_ENV)"
    fi
}

# Print input number in bold red if not zero
function bred_if_nz {
    if [ "$1" -gt 0 ]; then
        printf '\001\e[1;31m\002%3d\001\e[0m\002' "$1"
    else
        printf '%3d' "$1"
    fi
}

#------------------------------------------------------------------------------#
#-- Sources
#------------------------------------------------------------------------------#

# Source all .sh files in .bashrc.d
# Directory and files MUST be owned by current user
# and have 700 and 600 perms respectively
bashrcd=~/.bashrc.d
if [[ $(stat -c '%f' "$bashrcd") == 41c0 && -O "$bashrcd" ]]; then
    shopt -s nullglob
    for f in "$bashrcd"/*.sh; do
        [[ $(stat -c '%f' "$f") == 8180 && -O "$f" ]] && {
            source "$f"
        }
    done
    shopt -u nullglob
fi

source /etc/profile.d/vte.sh # Workaround the CWD bug in GNOME Terminal
source /usr/share/git-core/contrib/completion/git-prompt.sh

#------------------------------------------------------------------------------#
#-- Variables
#------------------------------------------------------------------------------#
export LANG=en_US.utf8
export EDITOR=vim
export LESS=FRXS
export HISTCONTROL=ignoredups:ignorespace

export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1

PROMPT_COMMAND='__git_ps1 "[\$(bred_if_nz \$?)]\$(venv_ps1)" "[\u@\h \W]\\$ " "[%s]";'"$PROMPT_COMMAND"
export PROMPT_COMMAND

#------------------------------------------------------------------------------#
#-- Options
#------------------------------------------------------------------------------#
shopt -s direxpand
