- name: Bash configuration
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:

  - name: User facts
    setup:
      filter: '*user*'

  - name: User info
    set_fact:
      homedir: '{{ ansible_facts.user_dir }}'

  - name: Main .bashrc file
    copy:
      src: bashrc
      dest: '{{ homedir }}/.bashrc'
      mode: 0644

  - name: Main .bashrc.d directory
    copy:
      src: bashrc.d/
      dest: '{{ homedir }}/.bashrc.d'
      directory_mode: 0700
      mode: 0600
