set nocompatible
let mapleader = " "

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-sensible'
Plug 'midchildan/ft-confluence.vim'
Plug 'pedrohdz/vim-yaml-folds'
Plug 'haya14busa/vim-asterisk'
Plug 'jlanzarotta/bufexplorer'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf.vim'
Plug 'junegunn/gv.vim'
Plug 'Valloric/ListToggle'
Plug 'mtth/locate.vim'
Plug 'andymass/vim-matchup'
Plug 'preservim/nerdtree'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'jeetsukumaran/vim-pythonsense'
Plug 'junegunn/vim-peekaboo'
Plug 'wellle/visual-split.vim'
Plug 'Raimondi/delimitMate'
Plug 'hashivim/vim-terraform'
Plug 'easymotion/vim-easymotion'
Plug 'voldikss/vim-floaterm'

" Plug 'christoomey/vim-conflicted'
" Plug 'vim-scripts/repeatable-motions.vim'
" Plug 'tmhedberg/SimpylFold'
" Plug 'takac/vim-hardtime'
" Plug 'godlygeek/tabular'
" Plug 'wikitopian/hardmode'
call plug#end()

runtime! config/**/*.vim
