set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'

"Plug 'takac/vim-hardtime'
"Plug 'godlygeek/tabular'
"Plug 'vim-scripts/repeatable-motions.vim'
"Plug 'wikitopian/hardmode'
call plug#end()

" TEMPORARY FIX
" turning off indent
" because of misbehaviour on Fedora 31 and vim 8.2.694
" (indentexpr has bad handling of filetypes like sh and YAML)
filetype indent off

runtime! config/**/*.vim
