set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-sensible'
Plug 'midchildan/ft-confluence.vim'

"Plug 'takac/vim-hardtime'
"Plug 'godlygeek/tabular'
"Plug 'vim-scripts/repeatable-motions.vim'
"Plug 'wikitopian/hardmode'
call plug#end()

runtime! config/**/*.vim
